<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HamburgerMenu</name>
   <tag></tag>
   <elementGuidId>2fd196df-981b-40b7-aa7f-992541f46299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.toggle</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
